### ISSUE TITLE
Messages not being cleared after multiple attempts and restarts of OB

### ISSUE THREAD

**Issue by BugsBunE** [OpenBazaar/OpenBazaar-Client#1277] opened 2016-04-06 15:45 UTC
Brief Description: conversations are not being cleared from the message history, forced to restart OB multiple times doing the same process to remove the messages from the message history

Operating System (OS and version): win7 x64
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: 1.1.0 64x

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Almost always

Steps to reproduce:
1. send a few messages to another user
2. try to clear conversation
3. close OB and relaunch to find the message still there after being cleared from the first attempt

Observed Behavior:
message history seems to have a lag of not removing conversations properly

Expected Behavior:
conversations to be removed after clearing message history with user

**Comment by jjeffryes** [comment] 2016-04-06 15:48
Can you explain this issue with more detail? Are you clicking the "Clear Conversation" link in the chat sidebar, and the conversation is not being cleared?

**Comment by BugsBunE** [comment] 2016-04-06 15:49
@jjeffryes yes that is correct, the message clears from the sidebar, when i reload OB its back again

**Comment by jjeffryes** [comment] 2016-04-06 17:26
I can't reproduce this issue. We'll keep an eye on it and see if we can find out more about what's happening.

**Comment by MorgUK** [comment] 2016-04-08 09:53
I get the same issue.

**Comment by holtjohnson** [comment] 2016-04-13 21:27
Unable to reproduce. Tried multiple times.
Running OpenBazaar 1.1.2 on OSX 10.11.4

**Comment by SamPatt** [comment] 2016-05-26 19:21
Also cannot reproduce. I'm closing, @BugsBunE let us know if you're still able to reproduce on the current codebase.

**Closed as completed by SamPatt** 2016-05-26 19:21 UTC
Labels: Bug: please confirm
