### ISSUE TITLE
Names of countries are still not translatable

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1384] opened 2016-04-16 20:49 UTC
Names of countries ([countriesMd.js](https://github.com/OpenBazaar/OpenBazaar-Client/blob/master/js/models/countriesMd.js)) should be added to language files for translation.

**Comment by pryds** [comment] 2016-04-17 14:36
This issue might be a duplicate of part of issue #1179.

**Comment by rmisio** [comment] 2016-05-06 22:17
I'm working on this one.

**Comment by rmisio** [comment] 2016-05-19 18:28
this is fixed.

**Closed as completed** 2016-05-19 18:46 UTC
