### ISSUE TITLE
[Startup] Header image error

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Client#102] opened 2015-10-27 14:38 UTC
Not a bug exactly but if you start a fresh node and attempt to change the header image first, the client will give you an error saying that it needs a `name` and `location`, which are the constraints of the API. Something to be aware of in the future.

**Comment by jjeffryes** [comment] 2015-11-06 13:57
Duplicate of #90

**Closed as completed by jjeffryes** 2015-11-06 13:57 UTC
Labels: Bug: reproducible
