### ISSUE TITLE
Double Hyperlink Lines

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#784] opened 2016-02-23 21:09 UTC
Brief Description: I'm seeing double underlines in hyperlinks throughout the application.

Operating System (OS and version): OSX 10.11
OpenBazaar version (shown on `About OpenBazaar` page in menu): 0.9

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Go somewhere and hover over a link

Observed Behavior: It double underlines

Expected Behavior: Just one underline

Additional info (links, images, etc go here):
![image](https://cloud.githubusercontent.com/assets/45482/13266805/c9d622ca-da47-11e5-9760-28cdfe1c6d50.png)

**Comment by jjeffryes** [comment] 2016-02-23 21:13
Looks like a new bug in the tooltips.

**Comment by jjeffryes** [comment] 2016-02-23 21:44
Not a bug in tooltips per-se, it's a collision between the noOverflow and tooltip class. You can't use them together. I'm not sure why those elements have a tooltip, the tooltip just shows the same data.

It's fixed in my branch, I'll submit it with everything else.

**Closed as completed** 2016-02-23 22:19 UTC
