### ISSUE TITLE
Additional "UTC" bug in expiry times

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1723] opened 2016-06-24 09:35 UTC
Of all the online listings in [Duo Search](https://duosear.ch), below is a breakdown of the expiry timestamps:
- `never` -> 5352 times
- Some valid UTC timestamp -> 111 times
- `never UTC` -> 20 times
- `never UTC UTC` -> 57 times
- `never UTC UTC UTC` -> 13 times
- `never UTC UTC UTC UTC` -> 2 times
- `never UTC UTC UTC UTC UTC` -> 1 time
- `false UTC` 670

As can be seen, the string `UTC` gets spuriously added when the expiry is `never`. My theory is that listings with expiry set to `never` that get modified sometimes get an extra `UTC` added.

Looking at all Duo Search listings (not just those online) reveals other exceptional patterns:

`2016-05-03T15:49 UTC UTC` 3
`2019-11-21T00:00 UTC UTC` 12
`2016-06-17T11:10 UTC UTC` 10
`2017-03-23T00:00 UTC UTC` 12

`99999-02-12T09:09 UTC` 9
`2016-06-10 21:09:33 UTC` 1
`2016 UTC` 2

**Comment by sgornick** [comment] 2016-06-25 01:51
The root cause is in the API, reported as OpenBazaar-Server Issue # 439:
https://github.com/OpenBazaar/OpenBazaar-Server/issues/439

Though whether the client should do something when there is an invalid date could be a client issue.

**Comment by jjeffryes** [comment] 2016-08-10 15:44
I'm closing this issue, as it's tracked in the server repo.

**Closed as completed by jjeffryes** 2016-08-10 15:44 UTC
