### ISSUE TITLE
Different logos used in chat

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#917] opened 2016-03-02 13:40 UTC
The @helpdesk changed logo from white to red. The individual chat messages still use the old white logo, while the new logo is use as the cover image. See screenshot for discrepancy.

![screen shot 2016-03-02 at 14 39 26](https://cloud.githubusercontent.com/assets/731743/13461896/b8d7ed4e-e084-11e5-8722-a6995bb18763.png)

**Comment by jjeffryes** [comment] 2016-03-02 14:01
This is a duplicate of #881

**Closed as completed by jjeffryes** 2016-03-02 14:01 UTC
