### ISSUE TITLE
Time Zones still not translated

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1292] opened 2016-04-07 23:39 UTC
Time Zones on General Settings are still not translatable (don't have strings).

OB v1.1.2

**Comment by pryds** [comment] 2016-04-09 11:17
I believe this is a duplicate of issue #1179.

**Comment by Libter** [comment] 2016-04-16 11:32
This issue has been fixed in 3bdc86e781e48c53e4a1ec866c257e6089439f1b.

**Comment by jjeffryes** [comment] 2016-04-16 15:19
@programmerpeter is correct, I missed this issue when merging that code.

**Closed as completed by jjeffryes** 2016-04-16 15:19 UTC
