### ISSUE TITLE
Address bar input placeholder text only displaying when you're in Discover

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1406] opened 2016-04-20 16:23 UTC
See screenshots below, the placeholder text disappears when you move out of Discover

![screenshot 2016-04-20 09 22 03](https://cloud.githubusercontent.com/assets/13066886/14682227/7d7a67a6-06d9-11e6-8b72-72c7ef6eceb0.png)
![screenshot 2016-04-20 09 22 13](https://cloud.githubusercontent.com/assets/13066886/14682228/7d7d2dc4-06d9-11e6-800f-be719b4bc8c7.png)

**Comment by mariodian** [comment] 2016-04-21 01:24
I can't reproduce this issue on osx and the latest code from github.

**Comment by ghost** [comment] 2016-04-21 03:56
I also can't reproduce this issue in win7 64 bits v.1.1.3

**Comment by jjeffryes** [comment] 2016-04-21 18:11
I can reproduce this on master, it happens in settings and transactions.

I did a lot of testing on this, I can't really tell why it resets the placeholder in discover, but setting the address bar value to blank elsewhere doesn't.

**Comment by jjeffryes** [comment] 2016-04-21 18:21
Ridiculous answer: the theme module was setting the placeholder text to be white on a white background.

**Comment by jjeffryes** [comment] 2016-04-21 18:24
Fixed in 842209581becda2dae9820789c33d2b0eb0fce0a

**Closed as completed by jjeffryes** 2016-04-21 18:24 UTC
