### ISSUE TITLE
Order in two different states

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#1019] opened 2016-03-08 18:46 UTC
Something strange is going on. I bought a theme from @themes and the payment went through correctly (as seen below):

<img width="1280" alt="screenshot 2016-03-08 12 44 11" src="https://cloud.githubusercontent.com/assets/13066886/13612163/a027ee7e-e52b-11e5-93bc-cda126e31c4f.png">

I then went to the @themes node to confirm the order, but it's saying the order is in the Purchasing state.
<img width="1280" alt="screenshot 2016-03-08 12 44 19" src="https://cloud.githubusercontent.com/assets/13066886/13612176/ab47051a-e52b-11e5-9e9c-3f74e58439bc.png">

Both server nodes are on different ips and I'm connecting to them from my computer.

**Comment by morebrownies** [comment] 2016-03-08 18:47
I refreshed a few times as well on both sides and the states do not change

**Comment by jjeffryes** [comment] 2016-03-08 18:48
@cpacia thoughts here?

It looks to me like the @themes not isn't getting the update to the order.

**Comment by morebrownies** [comment] 2016-03-08 19:37
It looks like all my recent orders on @themes are showing in the Purchasing state

**Comment by jjeffryes** [comment] 2016-03-17 22:16
This appears to be a server issue with libbitcoin being very slow. I can reproduce it using a slow VPN, If the vendor marks the item as confirmed it updates to confirmed in the client.

**Comment by jjeffryes** [comment] 2016-03-17 22:18
I'm closing this, but opening an issue on the server, since it appears to be a server issue.

https://github.com/OpenBazaar/OpenBazaar-Server/issues/301

**Closed as completed by jjeffryes** 2016-03-17 22:18 UTC
