### ISSUE TITLE
Feature Request: ability to unfollow offline users

### ISSUE THREAD

**Issue by emeitner** [OpenBazaar/OpenBazaar-Client#1305] opened 2016-04-08 21:50 UTC
Brief Description: 
We should have the ability to unfollow offline users. One must visit the users page to unfollow them but this does not work when  they are offline.

OpenBazaar version (shown on `About OpenBazaar` page in menu):  1.1.2

Solution:
In the "Following" list on ones own page there should be an "unfollow" button for each user listed.  This should remove them from your "following" list whether or not they are online.

**Comment by ghost** [comment] 2016-04-08 23:03
Good point.

Also "Pages" tab in Discover show pages that are not followed AND pages that are  already followed.

If Discover purpose is to discover new pages, then it should show only pages that are currently not followed. 

If Discover purpose is to browse existing pages (followed) and discover new ones, maybe a solution would be adding in Pages a filter (Filtered Pages) just like the one already used in Listings (Filtered Listings).

**Comment by jjeffryes** [comment] 2016-04-09 03:38
This is a duplicate of #545. 

It's something we've discussed for some time.

**Closed as completed by jjeffryes** 2016-04-09 03:38 UTC
