### ISSUE TITLE
Spinner still spinning after clearing search

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#1048] opened 2016-03-09 19:59 UTC
Steps to repro:
- Go to Listings > Discover
- Enter a search query without results
- Clear the search using the X on the right side of the input box
- Notice the search query is cleared but the spinner keeps spinning indefinitely (see screenshot)

![screen shot 2016-03-09 at 20 56 53](https://cloud.githubusercontent.com/assets/731743/13648599/c63cf5be-e639-11e5-9d58-bb812ce24047.png)

**Comment by drwasho** [comment] 2016-03-10 00:42
Can't reproduce this, but perhaps this was fixed in one of the latest commits. @jjeffryes @SamPatt @morebrownies can you check?

**Comment by jjeffryes** [comment] 2016-03-10 01:08
It's possible if you clear the search before it's completed, and the normal load of the discover tab doesn't return any results due to network issues, the spinner could linger.

I can't reproduce it.

**Comment by JustinDrake** [comment] 2016-03-10 19:47
@jjeffryes: That's what I'm seeing. Relatively easy to repro for me.

**Comment by drwasho** [comment] 2016-03-24 07:27
This has been fixed.

**Closed as completed by drwasho** 2016-03-24 07:27 UTC
Labels: Bug: please confirm
