### ISSUE TITLE
User-input capitalization isn't saved for store names or product names

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Client#234] opened 2015-11-18 22:57 UTC
Uppercase letters are ignored other than the first character on store titles and listing titles. So when I tried to put in "OB Comic Book Store" it shows "Ob" instead. Also, in the main listing page something that should show as "Rare She-Hulk Comic" displays as "Rare she-hulk comic'

**Comment by drwasho** [comment] 2015-11-18 23:19
Duplicate of #160

**Closed as completed by drwasho** 2015-11-18 23:19 UTC
Labels: Bug: reproducible
