### ISSUE TITLE
Customizing your page fails if you haven't set a store name yet

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Client#86] opened 2015-10-26 14:46 UTC
I believe this will be resolved by the onboarding wizard?

**Comment by morebrownies** [comment] 2015-11-04 15:21
Would it make sense to have the server automatically set a name upon guid creation? Ideally, it would generate something like Anon89234 (last 5 digits of the guid) and the user could override it at any point. I think it would be ideal for every node to have a name and not rely on the client application to generate one.

**Comment by jjeffryes** [comment] 2015-11-06 13:58
Duplicate of #90

**Closed as completed by jjeffryes** 2015-11-06 13:58 UTC
Labels: Bug: reproducible
