### ISSUE TITLE
Allow publish / unpublish per listing

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1650] opened 2016-06-03 02:13 UTC
Each listing should have its own _publish / unpublish_ option on "edit listing" page.
Currently only all listings as a whole can be published / unpublished by activating / deactivating store on Settings page.

**Comment by sgornick** [comment] 2016-06-26 17:31
As OpenBazaar works today, a store that runs out of stock for an item must delete the listing to avoid there being any new orders placed for it.   So this issue reported affects so many OpenBazaar stores.

In the roadmap, under "short term" is "Inventory Management".

https://medium.com/@therealopenbazaar/openbazaar-roadmap-46b9e774f319#.ogizdfpl3

Perhaps this inventory management method would be how you would unpublish a listing.  Something like an inventory level of 0 would also "unpublish"?   Or perhaps a store would still want an out-of-stock item published -- just that with stock level of zero no buy order can be placed for it.

**Comment by jjeffryes** [comment] 2016-08-10 15:45
This is a duplicate of #531

**Closed as completed by jjeffryes** 2016-08-10 15:45 UTC
Labels: Enhancement/suggestion
