### ISSUE TITLE
When changing servers with the client it tries to connect to the last GUID it couldn't connect to.

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Client#1719] opened 2016-06-23 15:21 UTC
This can be very frustrating and pressing cancel usually starts the reconnect again. You have to wait for the resolve to fail and then press back to get back to your home page.

Can you just show your own store page on any reconnect from the client?

**Comment by rmisio** [comment] 2016-06-23 19:43
are you able to consistently reproduce this one?

It sounds like an edge case, because when you connect to a new server it just reloads the app where the app lands on whatever page you had been on. So, unless I'm missing something, in order for this to happen, you'd have to navigate to a user's page who is online, then while you're on that page the user goes offline, you connect to a new server and get the connecting screen.

Also, 'cancel' just takes you back to the previous page. Are you sure hitting cancel starts the reconnect again (to the same guid). I could see an edge case where 'cancel' does nothing, but the only way I see it initiating a reconnect to the same guid is if you have back to back duplicate entries for that guid in your browser history.

btw, are you on windows?

**Comment by dsmurrell** [comment] 2016-06-23 22:07
If it happens again, I'll try and get a video of it.

**Comment by sgornick** [comment] 2016-06-23 22:59
Is it possible you are switching between Testnet and Production?

I see this when switching back and forth from an OB server running on -testnet (because, of course, the GUIDs on testnet are invalid when on production, and vice-versa).

To avoid getting the "Connecting to [GUID]" followed, eventually, by "The page you're trying to view is currently offline" what I do is manually navigate to Discover / [Ctrl-D] before I switch servers that traverse testnet/production.

**Comment by dsmurrell** [comment] 2016-06-30 08:53
No, all servers are mainnet. I keep having this issue and now another person (bazaarcity.io) is having it too. Can we get the client to visit the page of the server it's connecting to when you connect to a server? I've been forgetting to take a video since I found out how to get around it with cmd-t

**Comment by benvhodl** [comment] 2016-06-30 08:54
We have the same annoying issue. Since we run multiple OB servers, every time we switch server on the client side, the new server reloads the previous page, while you would expect to load the new server's own page. Maybe this standard behavior can be changed?

**Comment by sgornick** [comment] 2016-06-30 17:01
> Can we get the client to visit the page of the server it's connecting to when you connect to a server? 

I can't think of a reason that shouldn't be the desired and expected behavior, by default.

**Comment by jjeffryes** [comment] 2016-09-29 20:32
This was closed by #1784

**Closed as completed by jjeffryes** 2016-09-29 20:32 UTC
