### ISSUE TITLE
Cannot set refund address

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#601] opened 2016-01-28 13:32 UTC
I've been trying to buy stuff but it always fails on the refund address

![screen shot 2016-01-28 at 14 31 59](https://cloud.githubusercontent.com/assets/731743/12645665/e6ea40b6-c5cb-11e5-8707-c637a3a0faf7.png)

**Comment by SamPatt** [comment] 2016-01-28 14:44
This is likely because the address entered isn't a valid one. Could be because it's not a testnet address and you're running on the testnet.

This does bring up a good issue though @jjeffryes. Right now in settings if you try to change one setting, such as language, and save it without entering a valid refund address, it won't let you save. Since the buying process forces users to put in a valid address we probably don't need to force that field in settings to be filled in order to save.

**Comment by JustinDrake** [comment] 2016-01-28 14:49
@SamPatt: I used a testnet address, and I'm running on testnet.

**Comment by jjeffryes** [comment] 2016-01-28 15:29
@JustinDrake can you post the address you used? I haven't been able to reproduce this issue.

@SamPatt I agree, I'll set the refund address in settings to be non-required.

**Comment by jjeffryes** [comment] 2016-01-29 04:24
So far this bug can't be reproduced, I am closing it, reopen it with a testnet address that doesn't work if it happens again.

**Closed as completed by jjeffryes** 2016-01-29 04:24 UTC
